FROM node:10.15-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install && npm install --unsafe-perm -g node-sass && npm cache clean --force

COPY . .

CMD ["npm","run","watch"]