FROM node:10.15-alpine

EXPOSE 8080

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install && npm install --unsafe-perm -g live-server && npm cache clean --force

COPY . .

CMD ["npm","run","live"]