version: "3"
services:
  sass:
    container_name: sass
    build:
      dockerfile: Dockerfile.devSass
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - test
  live:
    container_name: live
    build:
      dockerfile: Dockerfile.devServer
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - test

networks:
  test:
    driver: bridge

volumes:
  data:
    driver: local
